# Generated by Django 3.1.7 on 2023-12-03 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('society', models.CharField(max_length=255)),
                ('area_type', models.CharField(max_length=255)),
                ('availability', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('size', models.CharField(max_length=255)),
                ('bathrooms', models.IntegerField()),
                ('balcony', models.IntegerField()),
                ('area', models.CharField(max_length=255)),
            ],
        ),
    ]
