# Generated by Django 3.1.7 on 2023-12-05 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20231204_0500'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyImageName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='property_images/')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_names', to='main.property')),
            ],
        ),
    ]
