# Generated by Django 3.1.7 on 2023-12-05 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_propertyimagename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyimagename',
            name='image',
        ),
        migrations.AddField(
            model_name='propertyimagename',
            name='image_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
