# Generated by Django 5.0 on 2024-01-30 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_property_availability_remove_property_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='ready_to_move',
            field=models.BooleanField(),
        ),
    ]
