# Generated by Django 5.0 on 2024-02-03 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_property_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='balcony',
            field=models.IntegerField(null=True),
        ),
    ]
