# Generated by Django 5.0 on 2024-02-03 18:17

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_property_address_alter_property_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.ImageField(upload_to=main.models.property_subfolder),
        ),
    ]
