# Generated by Django 5.0 on 2024-03-18 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_property_latitude_alter_property_longitude'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='area_type',
            new_name='home_type',
        ),
        migrations.RemoveField(
            model_name='property',
            name='date_of_availability',
        ),
        migrations.RemoveField(
            model_name='property',
            name='ready_to_move',
        ),
    ]
